#!/bin/bash

_useEXE=""
_buildType="Debug"    #MSVC specific build configuration. Options: "Release" "Debug" "MinSizeRel" "RelWithDebInfo"


if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
    _useEXE=".exe" 
fi

cd ..

if [ ! -d "./cmake" ]; then
    mkdir "cmake"
    cd "cmake"
    "cmake"$_useEXE "../"
    cd ..
fi

cd "cmake"

if [ ! -d "./sandbox" ]; then
    mkdir "sandbox"
fi
"cmake"$_useEXE  --build . --config $_buildType

cd ..